#cloud-config

# On met à jour le système
  package_update: true
  package_upgrade: true

# On créé l'utilisateur avec droits sudo en précisant sa clé SSH publique
  users:
    - default
    - name: admindo
      lock_passwd: false
      passwd: $6$0Ma3rOkzE3prIHYB$M3k3vGXF/BEx.qlaU14CfRX0Dhh0.6XQcGUlWgFOrTnuHIO1mXWRP1KSji14HGo3qNu7gLNm8JdqjRR1HMBVI1
      groups: [ wheel , sudo ]
      shell: /bin/bash
      homedir: /home/admindo
      sudo: ['ALL=(ALL) NOPASSWD:ALL']
      #ssh_authorized_keys:
      #  - collez ici le contenu de votre clé publique

# Langues fr + clavier fr
  locale: fr_FR.UTF-8
  keyboard:
    layout: fr

  network:
  version: 2
  ethernets:
    # opaque ID for physical interfaces, only referred to by other stanzas
    eth0:
      dhcp4: false
      addresses:
        - 192.168.1.0/24
      gateway4: 192.168.1.254
      nameservers:
        search: [zouz.local]
        addresses: [8.8.8.8]
  