--- 
- name: Add config ip
  copy:
    dest: "/etc/netplan/50-cloud-init.yaml"
    content: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              eth0:
                dhcp4: no
                addresses:
                  - 192.168.1.1/24
                gateway4: 192.168.1.254
                nameservers:
                    addresses: [8.8.8.8, 1.1.1.1]

- name: Apply netplan
  command: sudo netplan apply
  ignore_errors: true
